source = ~/.config/hypr/theme.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windowrules.conf

exec-once = waybar
exec-once = hyprpaper
exec-once = dunst

monitor = ,preferred,auto,1

input {
    kb_layout = us
    follow_mouse = 1

    touchpad {
        natural_scroll = true
        tap-to-click = true
    }
}
