general {
    gaps_in = 6
    gaps_out = 12
    border_size = 2
    col.active_border = rgba(67c7e8ff) rgba(b46cffff) 45deg
    col.inactive_border = rgba(363a7a88)
    layout = dwindle
}

decoration {
    rounding = 14
    active_opacity = 0.96
    inactive_opacity = 0.88

    blur {
        enabled = true
        size = 7
        passes = 3
        new_optimizations = true
    }

    shadow {
        enabled = true
        range = 18
        render_power = 3
        color = rgba(00000055)
    }
}

animations {
    enabled = true

    bezier = smooth, 0.25, 0.1, 0.25, 1.0

    animation = windows, 1, 5, smooth
    animation = windowsIn, 1, 5, smooth, slide
    animation = windowsOut, 1, 4, smooth, slide
    animation = border, 1, 8, smooth
    animation = fade, 1, 6, smooth
    animation = workspaces, 1, 5, smooth
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}
