windowrule {
    match:class = ^(pavucontrol)$
    float = on
    size = 760 520
    center = on
}

windowrule {
    match:class = ^(blueman-manager)$
    float = on
    center = on
}

windowrule {
    match:class = ^(nm-connection-editor)$
    float = on
    size = 900 620
    center = on
}

windowrule {
    match:class = ^(kitty)$
    opacity = 0.94 0.88
}

windowrule {
    match:class = ^(rofi)$
    float = on
    opacity = 0.95 0.95
}

windowrule {
    match:class = ^(dunst)$
    float = on
    pin = on
}
