windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = size 760 520, class:^(pavucontrol)$
windowrulev2 = center, class:^(pavucontrol)$

windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = center, class:^(blueman-manager)$

windowrulev2 = opacity 0.94 0.88, class:^(kitty)$

windowrulev2 = float, class:^(rofi)$
windowrulev2 = opacity 0.95 0.95, class:^(rofi)$

windowrulev2 = float, class:^(dunst)$
windowrulev2 = pin, class:^(dunst)$
