windowrule {
    name = pavucontrol-float
    match:class = ^(pavucontrol)$
    float = on
    size = 760 520
    center = on
}

windowrule {
    name = blueman-manager-float
    match:class = ^(blueman-manager)$
    float = on
    center = on
}

windowrule {
    name = nm-connection-editor-float
    match:class = ^(nm-connection-editor)$
    float = on
    size = 900 620
    center = on
}

windowrule {
    name = wdisplays-float
    match:class = ^(wdisplays)$
    float = on
    size = 900 620
    center = on
}

windowrule {
    name = nwg-displays-float
    match:class = ^(nwg-displays)$
    float = on
    size = 900 620
    center = on
}

windowrule {
    name = display-fallback-float
    match:class = ^(big-sur-displays)$
    float = on
    size = 720 480
    center = on
}

windowrule {
    name = kitty-opacity
    match:class = ^(kitty)$
    opacity = 0.94 0.88
}

windowrule {
    name = rofi-float
    match:class = ^(rofi)$
    float = on
    opacity = 0.95 0.95
}

windowrule {
    name = dunst-pin
    match:class = ^(dunst)$
    float = on
    pin = on
}
